### ISSUE TITLE
After installing a new language. Content is not discovered

### ISSUE THREAD

**Issue by aDaneInSpain** [Jensen-Technologies/neno#115]
com_content is empty for instance, but full in the first language that was installed during installation.

**Comment by aDaneInSpain** [comment]
Even when clicking scan for content, no content is added.

**Comment by vistiyos** [comment]
@aDaneInSpain  Could you post some screenshot please? I need more information.

**Comment by vistiyos** [comment]
The screenshot should show the "Groups & Elements" view.

**Comment by vistiyos** [comment]
Solved on these commits: b19132c73f425c9b541cb1518a8f62b4224daeab 719dcf4dd1cfce1ac0f2ad0ed809589a076eea48
