### ISSUE TITLE
Purchased TC does not show up for user

### ISSUE THREAD

**Issue by aDaneInSpain** [Jensen-Technologies/neno#120]
This is happening on the site http://ilodev522.cloudaccess.net/administrator/

**Comment by vistiyos** [comment]
@aDaneInSpain I cannot access to the site to verify that

**Comment by vistiyos** [comment]
Now I'm able to access

**Comment by vistiyos** [comment]
Closed on fae4bda7f991260297321d21c05329e1c5710a5c
