### ISSUE TITLE
When loading existing translation into the editor the HTML is stripped

### ISSUE THREAD

**Issue by aDaneInSpain** [Jensen-Technologies/neno#125]

**Comment by vistiyos** [comment]
@aDaneInSpain did you fix this issue, didn't you?

**Comment by aDaneInSpain** [comment]
It will be fixed when the new editor is launched yes. Not sure about current version, but I think it is also fixed.

**Comment by vistiyos** [comment]
This issue has been fixed on 8446e3c1e79a6324ec16725da9ae3666acaf372d
