### ISSUE TITLE
PHP Warnings on foreach()

### ISSUE THREAD

**Issue by acs-ferreira** [Jensen-Technologies/neno#127]
My PHP log quicly fills up with messages like

````Invalid argument supplied for foreach() in libraries/neno/content/element/group.php on line 476````

What about not allocating an empty array when you've got nothing to begin with anyway ?

````
foreach ((array) $this->tables as $table) {
}
````

instead of

````
foreach ($this->tables as $table) {
}
````

If we cast any value to an array, we will get an array whatever value it was, avoiding these warnings.

**Comment by aDaneInSpain** [comment]
Thank you @acs-ferreira we fix this issue.

**Comment by vistiyos** [comment]
@acs-ferreira Thank you again. This patch will be included on the next maintenance version of Neno. Stay tuned
