### ISSUE TITLE
Problem saving category with Akeeba Release System

### ISSUE THREAD

**Issue by carcam** [Jensen-Technologies/neno#131]
## Description
When tryting to save a category in Akeeba Release System, the server validation fails saying "empty title" and it's impossible to create a category. I need to check the site without nene to see if this only happens when Neno is installed.

## Step by step 
The process I followed is:

1. Install Yootheme package with template
2. Update everything that needs to be updated
3. Install Neno
4. Install Akeeba Release System
5. Try to add a new category to ARS

## Other actions
I've also tried disabling ARS tables from Neno to check if that fixed the issue, but it does not.

## Further check
To be 100% sure this is Neno's interferring I'm going to do the whole process without neno and will see if the problem persists (which will indicate it's ARS and not neno's problem)

**Comment by vistiyos** [comment]
@carcam Thank you for this bug report. I will look into and I write here what I find
