### ISSUE TITLE
Installation step 5 - Explain "Do not translate" tab

### ISSUE THREAD

**Issue by Devportobello** [Jensen-Technologies/neno#202]
When installing neno translate, at step 5 there is a tab called "Do not translate", is it possible to translate ? and to explain more about this tab ?
[See here](https://github.com/Jensen-Technologies/neno/blob/19722ee1aaa122d97fc8d0910b0d2d786ad577e8/layouts/libraries/neno/installationstep5.php#L55)

**Comment by vistiyos** [comment]
@Devportobello Neno groups all the database tables and language files that should not be translate, but once you finish the installation, you can move those tables and file to the group that prefer. Currently there's no option to do that during installation, but we think it's a good idea to have it in Neno.

**Comment by Devportobello** [comment]
i will take for example "com_menu", is it a prerequisites to NOT translate at all items ?
The "Do not translate" tab is just a name or an obligation ?

**Comment by vistiyos** [comment]
@Devportobello It's just a name for that group. You can change it, even assign translation methods to it if you want.

**Comment by Devportobello** [comment]
@vistiyos Thanks for your response :)
I got one last question (maybe out of this issue sry):
Before installing Neno, did we need to setup for at least 1 language a default menu item ?
EG: having 1 default menu item to lang "all" and 1 default menu item to lang "EN" ?

**Comment by vistiyos** [comment]
@Devportobello Neno takes care of that, it transforms all the menu items set as "All" to the source language, and it replicates every single menu item to each language installed.

**Comment by Devportobello** [comment]
@vistiyos well i understand my mistake now ^^ thx alot
I close this.
