### ISSUE TITLE
2 general questions related to core strings.

### ISSUE THREAD

**Issue by MATsxm** [Jensen-Technologies/neno#213]
**1. - PITA question about code styling in the .ini files.**
Sometimes, strings appear like this:
`COM_NENO_DEBUG_PRIORITY_ENTRY_INFO = "Info"`
or
`COM_NENO_DEBUG_PRIORITY_ENTRY_INFO="Info"` (check the spaces between the key and the value).
What do YOU prefer to use?

**2. - Proposal for :uk: source styling**
I would suggest, as this becomes a habit in the l10n sphere, to abandon the use of those "successfully" "success :" "with success" which are unnecessary and redundant.
Just a proposal. :wink:

**Comment by aDaneInSpain** [comment]
I personally prefer `COM_NENO_DEBUG_PRIORITY_ENTRY_INFO = "Info"` and I like the idea of moving away from "success" but to what? How would you say it?

**Comment by MATsxm** [comment]
:smile: 
Nothing... this **IS** the point!

see: `"%d items successfully archived"`
the items are archived or not?
Doesn't make sense, or at least it is redundant. If the items are archived, then of course it is successfully or it would be "has not been archived" or kind of.

More and more, and I really DO THINK it is good, we are seeing kind of strings like:
`"%d items archived"`
nothing more is needed as it says what it did.

Maybe @brianteeman has an opinion on this point?

**Comment by brianteeman** [comment]
As a general rule I think the use of successfully is redundant. When I reviewed the usage in Joomla core it could be removed in about 80% of cases but not in all cases so it can not be a blind search and replace

**Comment by MATsxm** [comment]
> it can not be a blind search and replace

Sure thing

**Comment by MATsxm** [comment]
Thanks - Closed
