### ISSUE TITLE
Release notes link

### ISSUE THREAD

**Issue by bazric** [Jensen-Technologies/neno#41]
The release notes link on the Neno website when you download Neno does not work.

**Comment by davidvweb** [comment]
Do we have a linkfor this, @vistiyos ?

**Comment by vistiyos** [comment]
Currently it's just an nothing link, but I don't know if there is any design made for that. @davidvweb @bazric

**Comment by davidvweb** [comment]
@vistiyos I think my question was not clear: Are the release notes stored anywhere (inside or outside GitHub) so we can link to them from the website? If so, what is the URL?

**Comment by vistiyos** [comment]
Release notes is a field on the database of Neno-Translate that have been written by myself, so I don't think they aren't good enough to show to the public. I would recommend to have like Production meetings every week or every 2 weeks to plan what is going to be included on the next release, when we are going to publish it and then @bazric can write those release notes properly. What do you think @davidvweb @aDaneInSpain ?

**Comment by davidvweb** [comment]
@vistiyos Absolutely.

I will remove the link in the meantime.
