### ISSUE TITLE
Chinese does not work

### ISSUE THREAD

**Issue by bazric** [Jensen-Technologies/neno#43]
When I try to translate my site into Chinese, I just get a message saying "Neno is currently preparing this language for use.Please try again in a few minutes

**Comment by bazric** [comment]
Same for  Armenian

**Comment by bazric** [comment]
And Welsh......

**Comment by vistiyos** [comment]
@bazric When you install a new language, takes some time to complete the installation (Discover content, assigning translations methods), so that is the reason why that messages appears when you click on a message that is not ready yet. This makes sense for you?

**Comment by bazric** [comment]
Then the message should say "Neno is currently preparing this language for
use.Please try again in a few hours" because it takes hours not minutes.

**Comment by bazric** [comment]
And welsh still does not work. I just get this
http://i.imgur.com/hoqoIXy.png

**Comment by vistiyos** [comment]
@bazric I have tried installing a language, and normally takes a few minutes to complete, depends of how you are running background task. If you are using **AJAX** , the task wouldn't be completed until you browse enough on your site, but if you have set to run using **cronjobs**, it will completed on a few minutes.

**Comment by bazric** [comment]
o.k Thanks victor, good to know.

**Comment by vistiyos** [comment]
@bazric I have detected the same issue for me for Welsh, let me have a look at it.

**Comment by vistiyos** [comment]
@bazric I have a look why Welsh language is not detected by Neno, it seems the issue came from the Welsh language package. Every language package has to have a XML file that stores some metadata of the languages, but Welsh language pack doesn't have that metadata. In this case, I will report this issue to the Translation team. Thank you Barry
