### ISSUE TITLE
Data modeling for translator context

### ISSUE THREAD

**Issue by vistiyos** [Jensen-Technologies/neno#49]

**Comment by davidvweb** [comment]
@vistiyos  Please take a look to my comments here: https://github.com/Jensen-Technologies/neno/issues/51

**Comment by vistiyos** [comment]
This feature has been added on this commit 4ef730d080318a7d1d1001f138353e4bba10b00c

**Comment by vistiyos** [comment]
The feature hasn't been finished yet.
