### ISSUE TITLE
Implement interfaces to add context for external translators

### ISSUE THREAD

**Issue by vistiyos** [Jensen-Technologies/neno#51]
Do after #50

**Comment by davidvweb** [comment]
@vistiyos Pass stored comment to languageconfiguration layout on $displayData['comment']

**Comment by davidvweb** [comment]
@vistiyos In externaltranslations view, stored comment is should be put in 
```php
$comment
```

**Comment by davidvweb** [comment]
@vistiyos Pass stored comment to editor layout on 
```php
$displayData['comment']
```

**Comment by davidvweb** [comment]
@vistiyos All layout implementation has been pushed to https://github.com/Jensen-Technologies/neno/tree/feature/comments-to-translators
