### ISSUE TITLE
Show an alert when leaving the translation view with unsaved changes

### ISSUE THREAD

**Issue by aDaneInSpain** [Jensen-Technologies/neno#62]
When using the translation view and content has changed in the translation textarea. Show an alert before allowing loading a new variable into the field or leaving the page.

Alert should say:

You have unsaved changes! Are you sure you would like to continue without saving?

[Continue] [Cancel] 

Cancel should be default.

**Comment by vistiyos** [comment]
Closed on 26eabb40611409c4b34705f98a283ac368c4e48f by @davidvweb
