### ISSUE TITLE
By default unknown components should be set to "Do not translate"

### ISSUE THREAD

**Issue by aDaneInSpain** [Jensen-Technologies/neno#65]
As @brianteeman suggested. This will be a temporary solution until we implement a dialog for asking during the installation phase.

**Comment by vistiyos** [comment]
@aDaneInSpain So components that we don't have any content element files, we mark it as "Do not translate", am I right?

**Comment by aDaneInSpain** [comment]
Correct. But still process the fields so we mark INT as do not translate and VARCHAR as translate for instance so if the user decides to enable the component we will by default be mostly correct in what needs to be translated. And remember the long term solution for a later version will be to ask the user what he would like to do with the unknown component.

**Comment by vistiyos** [comment]
Ok
