### ISSUE TITLE
untranslatable content 

### ISSUE THREAD

**Issue by bazric** [Jensen-Technologies/neno#77]
These fields in these tables should be set to not be translated by default.
Other #__ak_profiles configuration 
Akeeba #__akeeba_common value 
com_categories #__categories metadata
com_content #__content metadata  
Other #__ak_stats absolute_path 
Other #__ak_stats archivename  
Other #__ak_stats backupid

**Comment by vistiyos** [comment]
@bazric Would you mind to create a content element files for them?

**Comment by vistiyos** [comment]
@bazric Which one should be assigned to this card?

**Comment by bazric** [comment]
here they are. I set them up ready to go

**Comment by vistiyos** [comment]
@bazric Please forward them to my email please
