### ISSUE TITLE
If the user creates a new menu item, Neno should take care of that. The plugin will be triggered on that event, I think.

### ISSUE THREAD

**Issue by vistiyos** [Jensen-Technologies/neno#95]

**Comment by aDaneInSpain** [comment]
I am not totally sure what the question is, but yes. A plugin should keep the menu intact and duplicated. But also remember that redComponent solved translating menu's. Maybe we could peek at their code and see how they solved it?

**Comment by vistiyos** [comment]
Currently I'm waiting to that guys that said he will get in contact with me on JAB15

**Comment by aDaneInSpain** [comment]
We can peek in their code without him. He is too busy.

**Comment by vistiyos** [comment]
@aDaneInSpain could you try to find that code while I'm working on the other issues?

**Comment by aDaneInSpain** [comment]
OK

**Comment by vistiyos** [comment]
@aDaneInSpain I've been investigating and Joomla trigger an event when it saves a menu item. I guess we can use that, don't you think?

**Comment by aDaneInSpain** [comment]
Yes. We have it working well with replicating menus, so lets stick with that. Back to you.
