### ISSUE TITLE
New content is not detected through Task Queue

### ISSUE THREAD

**Issue by vistiyos** [Jensen-Technologies/neno#96]

**Comment by aDaneInSpain** [comment]
I think this would be great to have covered with the automatic testing. Create an article and search for the content in the editor.

I also think it would be a good idea to include a "Scan for new content" on a per table basis from Groups and elements when users KNOW there is new content.

**Comment by vistiyos** [comment]
@aDaneInSpain It only can be achieve if the extension (com_content does) throw "onContentAfterSave" event. Otherwise it will discover by the Task Queue, and it was configured to run by AJAX, it would take more time that if it's configured to use CRON jobs.

**Comment by vistiyos** [comment]
@aDaneInSpain please have a look to #97

**Comment by vistiyos** [comment]
This is closed on c1d8c6cc31a2a6ad9c86c8cec7e1666ca54e11e7
