### ISSUE TITLE
Translation view filter not applied on page load

### ISSUE THREAD

**Issue by aDaneInSpain** [Jensen-Technologies/neno#99]
When applying a filter to only translate one table the interface correctly filters the list of strings. But when reloading the view the filter is still applied but content from several tables are shown. @bazric found this issue

**Comment by vistiyos** [comment]
@davidvweb I have fixed the issue filtering strings but what I cannot make work is if a field has been marked, span its parent (table). I have applied expanded class to that node but still doesn't work. would you mind to have a look?
